repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.14
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [
          types-toml==0.10.8.7,
          types-colorama==0.4.15.20240106,
          aiohttp==3.9.1,
          platformdirs==4.1.0,
          pygobject==3.46.0,
          typer==0.9.0,
          rich==13.7.0,
          types-psutil==5.9.5.20240106,
          setproctitle==1.3.3
        ]
